// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Infrastructure.Migrations
{
    [DbContext(typeof(ArticleOfferContext))]
    [Migration("20241116164820_Inital")]
    partial class Inital
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Infrastructure.Models.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ArticleDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ArticleName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleDescription = "desc1",
                            ArticleName = "item1",
                            Price = 10m
                        },
                        new
                        {
                            Id = 2,
                            ArticleDescription = "desc1",
                            ArticleName = "item2",
                            Price = 22m
                        },
                        new
                        {
                            Id = 3,
                            ArticleDescription = "desc1",
                            ArticleName = "item3",
                            Price = 3m
                        },
                        new
                        {
                            Id = 4,
                            ArticleDescription = "desc1",
                            ArticleName = "item4",
                            Price = 40m
                        },
                        new
                        {
                            Id = 5,
                            ArticleDescription = "desc1",
                            ArticleName = "item5",
                            Price = 52m
                        },
                        new
                        {
                            Id = 6,
                            ArticleDescription = "desc1",
                            ArticleName = "item6",
                            Price = 62m
                        },
                        new
                        {
                            Id = 7,
                            ArticleDescription = "desc1",
                            ArticleName = "item7",
                            Price = 17m
                        },
                        new
                        {
                            Id = 8,
                            ArticleDescription = "desc1",
                            ArticleName = "item8",
                            Price = 28m
                        },
                        new
                        {
                            Id = 9,
                            ArticleDescription = "desc1",
                            ArticleName = "item9",
                            Price = 39m
                        },
                        new
                        {
                            Id = 10,
                            ArticleDescription = "desc1",
                            ArticleName = "item10",
                            Price = 10m
                        },
                        new
                        {
                            Id = 11,
                            ArticleDescription = "desc1",
                            ArticleName = "item11",
                            Price = 11m
                        },
                        new
                        {
                            Id = 12,
                            ArticleDescription = "desc1",
                            ArticleName = "item12",
                            Price = 1m
                        },
                        new
                        {
                            Id = 13,
                            ArticleDescription = "desc1",
                            ArticleName = "item13",
                            Price = 21m
                        },
                        new
                        {
                            Id = 14,
                            ArticleDescription = "desc1",
                            ArticleName = "item14",
                            Price = 22m
                        },
                        new
                        {
                            Id = 15,
                            ArticleDescription = "desc1",
                            ArticleName = "item15",
                            Price = 13m
                        },
                        new
                        {
                            Id = 16,
                            ArticleDescription = "desc1",
                            ArticleName = "item16",
                            Price = 100m
                        },
                        new
                        {
                            Id = 17,
                            ArticleDescription = "desc1",
                            ArticleName = "item17",
                            Price = 114m
                        },
                        new
                        {
                            Id = 18,
                            ArticleDescription = "desc1",
                            ArticleName = "item18",
                            Price = 13m
                        },
                        new
                        {
                            Id = 19,
                            ArticleDescription = "desc1",
                            ArticleName = "item19",
                            Price = 221m
                        },
                        new
                        {
                            Id = 20,
                            ArticleDescription = "desc1",
                            ArticleName = "item20",
                            Price = 111m
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.ArticleOfferItem", b =>
                {
                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("OfferId")
                        .HasColumnType("int");

                    b.Property<decimal>("Quantity")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("UnitPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("ArticleId", "OfferId");

                    b.HasIndex("OfferId");

                    b.ToTable("ArticleOfferItem");

                    b.HasData(
                        new
                        {
                            ArticleId = 1,
                            OfferId = 1,
                            Quantity = 2m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 4,
                            OfferId = 1,
                            Quantity = 4m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 8,
                            OfferId = 1,
                            Quantity = 1m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 20,
                            OfferId = 1,
                            Quantity = 2m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 18,
                            OfferId = 1,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 7,
                            OfferId = 1,
                            Quantity = 4m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 2,
                            OfferId = 1,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 15,
                            OfferId = 1,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 1,
                            OfferId = 2,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 4,
                            OfferId = 2,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 13,
                            OfferId = 2,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 15,
                            OfferId = 3,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 7,
                            OfferId = 4,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 2,
                            OfferId = 4,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 1,
                            OfferId = 5,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 1,
                            OfferId = 6,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 4,
                            OfferId = 6,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 3,
                            OfferId = 7,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 5,
                            OfferId = 8,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 10,
                            OfferId = 9,
                            Quantity = 32m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 1,
                            OfferId = 10,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 18,
                            OfferId = 10,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 11,
                            OfferId = 11,
                            Quantity = 33m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 12,
                            OfferId = 12,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 6,
                            OfferId = 13,
                            Quantity = 34m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 4,
                            OfferId = 14,
                            Quantity = 11m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 5,
                            OfferId = 14,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 12,
                            OfferId = 14,
                            Quantity = 4m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 8,
                            OfferId = 15,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 19,
                            OfferId = 16,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 19,
                            OfferId = 17,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 4,
                            OfferId = 18,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 2,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 6,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 7,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 11,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 12,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 14,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 15,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 18,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 19,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 20,
                            OfferId = 19,
                            Quantity = 3m,
                            UnitPrice = 10m
                        },
                        new
                        {
                            ArticleId = 10,
                            OfferId = 20,
                            Quantity = 3m,
                            UnitPrice = 10m
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.Offer", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("Date")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Offers");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Date = new DateTime(2024, 11, 1, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 2,
                            Date = new DateTime(2024, 11, 2, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 3,
                            Date = new DateTime(2024, 11, 3, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 4,
                            Date = new DateTime(2024, 11, 4, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 5,
                            Date = new DateTime(2024, 11, 5, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 6,
                            Date = new DateTime(2024, 11, 6, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 7,
                            Date = new DateTime(2024, 11, 7, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 8,
                            Date = new DateTime(2024, 11, 8, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 9,
                            Date = new DateTime(2024, 11, 9, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 10,
                            Date = new DateTime(2024, 11, 10, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 11,
                            Date = new DateTime(2024, 11, 11, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 12,
                            Date = new DateTime(2024, 11, 12, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 13,
                            Date = new DateTime(2024, 11, 13, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 14,
                            Date = new DateTime(2024, 11, 14, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 15,
                            Date = new DateTime(2024, 11, 15, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 16,
                            Date = new DateTime(2024, 11, 16, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 17,
                            Date = new DateTime(2024, 11, 17, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 18,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 19,
                            Date = new DateTime(2024, 11, 18, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        },
                        new
                        {
                            Id = 20,
                            Date = new DateTime(2024, 11, 20, 0, 0, 0, 0, DateTimeKind.Unspecified)
                        });
                });

            modelBuilder.Entity("Infrastructure.Models.ArticleOfferItem", b =>
                {
                    b.HasOne("Infrastructure.Models.Article", "Article")
                        .WithMany("ArticleOfferItems")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Infrastructure.Models.Offer", "Offer")
                        .WithMany("ArticleOfferItems")
                        .HasForeignKey("OfferId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Article");

                    b.Navigation("Offer");
                });

            modelBuilder.Entity("Infrastructure.Models.Article", b =>
                {
                    b.Navigation("ArticleOfferItems");
                });

            modelBuilder.Entity("Infrastructure.Models.Offer", b =>
                {
                    b.Navigation("ArticleOfferItems");
                });
#pragma warning restore 612, 618
        }
    }
}
